export const BeerActionTypes = {
  BEERS_FETCH_IF_NOT: "@BEERS/FETCH_IF_NOT",
  BEERS_FETCH: "@BEERS/FETCH",
  BEERS_FETCH_SUCCESS: "@BEERS/FETCH_SUCCESS",
  BEERS_FETCH_FAILURE: "@BEERS/FETCH_FAILURE",
  BEERS_SET: "@BEERS/SET",
  BEERS_CREATE: "@BEERS/CREATE",
  BEERS_SET_NEW: "@BEERS/SET_NEW",

  BEERS_UPDATE: "@BEERS/UPDATE",
  BEERS_UPDATE_SUCCESS: "@BEERS/UPDATE_SUCCESS",
  BEERS_UPDATE_FAILURE: "@BEERS/UPDATE_FAILURE",

  BEERS_DELETE: "@BEERS/DELETE",
  BEERS_DELETE_SUCCESS: "@BEERS/DELETE_SUCCESS",
  BEERS_DELETE_FAILURE: "@BEERS/DELETE_FAILURE",

  BEERS_RATE: "@BEERS/RATE",
  BEERS_RATE_SUCCESS: "@BEERS/RATE_SUCCESS",
  BEERS_RATE_FAILURE: "@BEERS/RATE_FAILURE",
  BEERS_SET_RATE: "@BEERS/SET_RATE",
};
